name: Warrior
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  dio: 
  lottie: 
  flutter_screenutil: 
  flutter_riverpod: 
  device_preview: 
  go_router: 
  flutter_native_splash: 
  flutter_launcher_icons: 
  change_app_package_name: 
  firebase_core: 
  flutter_dotenv: 
  google_fonts: 
  flutter_svg:
  page_transition: 
  another_flushbar: 
  smooth_page_indicator: 
  pinput: 
  otp_timer_button: 
  pretty_dio_logger: 
  flutter_secure_storage: 
  google_sign_in: 
  cached_network_image: 
  flutter_cache_manager: 
  hive: 
  hive_flutter: 
  connectivity_plus: 
  shared_preferences: ^2.3.5
  talker_dio_logger: ^4.6.7
  oktoast: ^3.4.0
  cached_video_player_plus: ^3.0.3
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 
  build_runner: 
  flutter_lints:
  # Testing dependencies
  mockito: ^5.4.4
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  fake_async: ^1.3.1
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/onboarding/
    - assets/images/signup/
    - assets/images/home/
    - assets/animation/
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    
    - family: Kings
      fonts:
        - asset: assets/fonts/Kings-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

