// Mocks generated by Mockito 5.4.4 from annotations
// in Warrior/test/unit/usecases/product_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:Warrior/features/FoodSearch/data/models/pending_product_upload.dart'
    as _i11;
import 'package:Warrior/features/FoodSearch/domain/entities/nutrition_facts.dart'
    as _i10;
import 'package:Warrior/features/FoodSearch/domain/entities/product_entity.dart'
    as _i2;
import 'package:Warrior/features/FoodSearch/domain/entities/search_history_entity.dart'
    as _i8;
import 'package:Warrior/features/FoodSearch/domain/repositories/product_read_repository.dart'
    as _i3;
import 'package:Warrior/features/FoodSearch/domain/repositories/product_write_repository.dart'
    as _i5;
import 'package:Warrior/features/FoodSearch/domain/repositories/user_interaction_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:openfoodfacts/openfoodfacts.dart' as _i6;

/// A class which mocks [ProductEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductEntity extends _i1.Mock implements _i2.ProductEntity {
  MockProductEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get barcode => (super.noSuchMethod(
        Invocation.getter(#barcode),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#barcode),
        ),
      ) as String);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  bool get hasBasicInfo => (super.noSuchMethod(
        Invocation.getter(#hasBasicInfo),
        returnValue: false,
      ) as bool);

  @override
  DateTime get lastUpdated => (super.noSuchMethod(
        Invocation.getter(#lastUpdated),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#lastUpdated),
        ),
      ) as DateTime);

  @override
  _i2.ProductEntity copyWith({
    String? barcode,
    String? productName,
    String? brands,
    String? quantity,
    String? imageUrl,
    String? nutriScore,
    int? novaGroup,
    String? ecoscore,
    _i10.NutritionFacts? nutrition,
    String? ingredients,
    List<String>? allergens,
    List<String>? additives,
    List<String>? categories,
    List<String>? labels,
    bool? isVegan,
    bool? isVegetarian,
    bool? palmOilFree,
    DateTime? lastUpdated,
    String? servingSize,
    String? packagingText,
    String? countries,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #barcode: barcode,
            #productName: productName,
            #brands: brands,
            #quantity: quantity,
            #imageUrl: imageUrl,
            #nutriScore: nutriScore,
            #novaGroup: novaGroup,
            #ecoscore: ecoscore,
            #nutrition: nutrition,
            #ingredients: ingredients,
            #allergens: allergens,
            #additives: additives,
            #categories: categories,
            #labels: labels,
            #isVegan: isVegan,
            #isVegetarian: isVegetarian,
            #palmOilFree: palmOilFree,
            #lastUpdated: lastUpdated,
            #servingSize: servingSize,
            #packagingText: packagingText,
            #countries: countries,
          },
        ),
        returnValue: _FakeProductEntity_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #barcode: barcode,
              #productName: productName,
              #brands: brands,
              #quantity: quantity,
              #imageUrl: imageUrl,
              #nutriScore: nutriScore,
              #novaGroup: novaGroup,
              #ecoscore: ecoscore,
              #nutrition: nutrition,
              #ingredients: ingredients,
              #allergens: allergens,
              #additives: additives,
              #categories: categories,
              #labels: labels,
              #isVegan: isVegan,
              #isVegetarian: isVegetarian,
              #palmOilFree: palmOilFree,
              #lastUpdated: lastUpdated,
              #servingSize: servingSize,
              #packagingText: packagingText,
              #countries: countries,
            },
          ),
        ),
      ) as _i2.ProductEntity);
}

/// A class which mocks [ProductReadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductReadRepository extends _i1.Mock
    implements _i3.ProductReadRepository {
  MockProductReadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ProductEntity>> compareProducts(List<String>? barcodes) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareProducts,
          [barcodes],
        ),
        returnValue:
            _i4.Future<List<_i2.ProductEntity>>.value(<_i2.ProductEntity>[]),
      ) as _i4.Future<List<_i2.ProductEntity>>);

  @override
  List<_i2.ProductEntity> getAllCachedProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedProducts,
          [],
        ),
        returnValue: <_i2.ProductEntity>[],
      ) as List<_i2.ProductEntity>);

  @override
  _i2.ProductEntity? getProductFromCache(String? barcode) =>
      (super.noSuchMethod(Invocation.method(
        #getProductFromCache,
        [barcode],
      )) as _i2.ProductEntity?);

  @override
  _i4.Future<List<String>> getProductSuggestions(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductSuggestions,
          [query],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  List<_i2.ProductEntity> getRecentlyScanned({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyScanned,
          [],
          {#limit: limit},
        ),
        returnValue: <_i2.ProductEntity>[],
      ) as List<_i2.ProductEntity>);

  @override
  _i4.Future<List<_i2.ProductEntity>> searchByBrand(
    String? brand, {
    int? page = 1,
    int? pageSize = 25,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByBrand,
          [brand],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ProductEntity>>.value(<_i2.ProductEntity>[]),
      ) as _i4.Future<List<_i2.ProductEntity>>);

  @override
  _i4.Future<List<_i2.ProductEntity>> searchByCategory(
    String? category, {
    int? page = 1,
    int? pageSize = 25,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByCategory,
          [category],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ProductEntity>>.value(<_i2.ProductEntity>[]),
      ) as _i4.Future<List<_i2.ProductEntity>>);

  @override
  _i4.Future<_i2.ProductEntity?> searchProductByBarcode(String? barcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProductByBarcode,
          [barcode],
        ),
        returnValue: _i4.Future<_i2.ProductEntity?>.value(),
      ) as _i4.Future<_i2.ProductEntity?>);

  @override
  _i4.Future<List<_i2.ProductEntity>> searchProductsByName(
    String? query, {
    int? page = 1,
    int? pageSize = 25,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProductsByName,
          [query],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ProductEntity>>.value(<_i2.ProductEntity>[]),
      ) as _i4.Future<List<_i2.ProductEntity>>);
}

/// A class which mocks [ProductWriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductWriteRepository extends _i1.Mock
    implements _i5.ProductWriteRepository {
  MockProductWriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> addNewProduct(
    _i2.ProductEntity? product,
    _i6.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNewProduct,
          [
            product,
            user,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  int getPendingProductCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingProductCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  List<_i11.PendingProductUpload> getPendingProductUploads() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingProductUploads,
          [],
        ),
        returnValue: <_i11.PendingProductUpload>[],
      ) as List<_i11.PendingProductUpload>);

  @override
  _i4.Future<bool> submitProduct({
    required _i2.ProductEntity? product,
    required _i6.User? user,
    String? imagePath,
    bool? isUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitProduct,
          [],
          {
            #product: product,
            #user: user,
            #imagePath: imagePath,
            #isUpdate: isUpdate,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateProduct(
    _i2.ProductEntity? product,
    _i6.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            product,
            user,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> uploadProductImage({
    required String? barcode,
    required String? imagePath,
    required _i6.ImageField? imageField,
    required _i6.User? user,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProductImage,
          [],
          {
            #barcode: barcode,
            #imagePath: imagePath,
            #imageField: imageField,
            #user: user,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i6.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get password => (super.noSuchMethod(
        Invocation.getter(#password),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#password),
        ),
      ) as String);

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  Map<String, String> toData() => (super.noSuchMethod(
        Invocation.method(
          #toData,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toValueString() => (super.noSuchMethod(
        Invocation.method(
          #toValueString,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #toValueString,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [UserInteractionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInteractionRepository extends _i1.Mock
    implements _i7.UserInteractionRepository {
  MockUserInteractionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> addToFavorites(_i2.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [product],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i2.ProductEntity> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <_i2.ProductEntity>[],
      ) as List<_i2.ProductEntity>);

  @override
  List<_i8.SearchHistoryEntity> getHistory({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
          {#limit: limit},
        ),
        returnValue: <_i8.SearchHistoryEntity>[],
      ) as List<_i8.SearchHistoryEntity>);

  @override
  bool isFavorite(String? barcode) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [barcode],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> removeFromFavorites(String? barcode) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [barcode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductEntity_1 extends _i1.SmartFake implements _i2.ProductEntity {
  _FakeProductEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
