// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQU7oXBNYnLqcJYZTQ0lwPTNFv0bOS680',
    appId: '1:466603345246:web:4f270bf25b72fed10a3bcf',
    messagingSenderId: '466603345246',
    projectId: 'warrior-dd0f2',
    authDomain: 'warrior-dd0f2.firebaseapp.com',
    storageBucket: 'warrior-dd0f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0_DBUzdBPaiQ3Jxt4BT3FeZaGkl82Jw',
    appId: '1:466603345246:android:a4d0161c402a1bd30a3bcf',
    messagingSenderId: '466603345246',
    projectId: 'warrior-dd0f2',
    storageBucket: 'warrior-dd0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9ivx-9WmypIsnP2fin9tyvc2r7Ji6-U',
    appId: '1:466603345246:ios:ad5703c1fcf027fc0a3bcf',
    messagingSenderId: '466603345246',
    projectId: 'warrior-dd0f2',
    storageBucket: 'warrior-dd0f2.firebasestorage.app',
    iosBundleId: 'com.Warrior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQU7oXBNYnLqcJYZTQ0lwPTNFv0bOS680',
    appId: '1:466603345246:web:c25255a30dfc07310a3bcf',
    messagingSenderId: '466603345246',
    projectId: 'warrior-dd0f2',
    authDomain: 'warrior-dd0f2.firebaseapp.com',
    storageBucket: 'warrior-dd0f2.firebasestorage.app',
  );

}