// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:Warrior/features/Exercises/data/models/exercise_model.dart';
import 'package:Warrior/features/Exercises/data/models/muscle_model.dart';
import 'package:Warrior/features/FoodSearch/data/models/favorite_food_model.dart';
import 'package:Warrior/features/FoodSearch/data/models/food_product_model.dart';
import 'package:Warrior/features/FoodSearch/data/models/nutrition_values_model.dart';
import 'package:Warrior/features/FoodSearch/data/models/pending_product_upload.dart';
import 'package:Warrior/features/FoodSearch/data/models/pending_upload_status.dart';
import 'package:Warrior/features/FoodSearch/data/models/product_data_source.dart';
import 'package:Warrior/features/FoodSearch/data/models/search_history_model.dart';
import 'package:Warrior/features/Workouts/data/models/exercise_set_record_model.dart';
import 'package:Warrior/features/Workouts/data/models/pending_operations_model.dart';
import 'package:Warrior/features/Workouts/data/models/workoutset_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExerciseModelAdapter());
    registerAdapter(ExerciseSetRecordModelAdapter());
    registerAdapter(FavoriteFoodModelAdapter());
    registerAdapter(FoodProductModelAdapter());
    registerAdapter(MuscleModelAdapter());
    registerAdapter(NutritionValuesModelAdapter());
    registerAdapter(PendingOperationAdapter());
    registerAdapter(PendingProductUploadAdapter());
    registerAdapter(PendingUploadStatusAdapter());
    registerAdapter(ProductDataSourceAdapter());
    registerAdapter(SearchHistoryModelAdapter());
    registerAdapter(SearchTypeAdapter());
    registerAdapter(SyncOperationTypeAdapter());
    registerAdapter(WorkoutItemModelAdapter());
    registerAdapter(WorkoutSetModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExerciseModelAdapter());
    registerAdapter(ExerciseSetRecordModelAdapter());
    registerAdapter(FavoriteFoodModelAdapter());
    registerAdapter(FoodProductModelAdapter());
    registerAdapter(MuscleModelAdapter());
    registerAdapter(NutritionValuesModelAdapter());
    registerAdapter(PendingOperationAdapter());
    registerAdapter(PendingProductUploadAdapter());
    registerAdapter(PendingUploadStatusAdapter());
    registerAdapter(ProductDataSourceAdapter());
    registerAdapter(SearchHistoryModelAdapter());
    registerAdapter(SearchTypeAdapter());
    registerAdapter(SyncOperationTypeAdapter());
    registerAdapter(WorkoutItemModelAdapter());
    registerAdapter(WorkoutSetModelAdapter());
  }
}
