# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane For Firebase Distribution"
  lane :fbd do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
      app: "1:466603345246:android:a4d0161c402a1bd30a3bcf",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "bombotuf15@gmail.com,mohamedbfc700@gmail.com,momenrefat977@gmail.com,ahmedkok980@gmail.com",
      release_notes: "First Release To Google Play",
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


end
