name: Google Play Store

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        default: 'internal'
        type: choice
        options:
        - internal
        - alpha
        - beta
        - production

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.32.0"
        channel: stable
        cache: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true
        working-directory: android
    - run: flutter pub get
    - name: Setup signing
      run: |
        mkdir -p android/app/keystore
        echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > android/app/keystore/upload-keystore.jks
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=keystore/upload-keystore.jks" >> android/key.properties
        echo '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}' > android/google-play-service-account.json
    - run: flutter build appbundle --release
    - run: bundle exec fastlane android deploy_to_play_store track:${{ github.event.inputs.track || 'internal' }}
      working-directory: android 